language: node_js
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '8'
branches:
  only:
    - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn run lint
  - yarn run build
  - yarn run test
after_success:
  - yarn run semantic-release
